/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bigbade.minecraftplugindevelopment;

import org.junit.Test;

/**
 * A simple unit test for the 'MinecraftPluginDevelopmentTest' plugin.
 */
public class MinecraftPluginDevelopmentTest {
    @Test
    public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        //Project project = ProjectBuilder.builder().build();
        //project.getPlugins().apply("MinecraftPluginDevelopment");

        // Verify the result
        // assertNotNull(project.getTasks().findByName("greeting"));
    }
}
